# Pandas Project

# 1. Problem Statement

Streaming platforms contain thousands of movies and TV shows produced across different countries and genres.

Analyzing this data helps answer important questions such as:

- Which type of content dominates the platform?
- Which countries produce the most content?
- What genres are the most popular?
- How has content production changed over time?
- Which content receives the highest number of views?

The goal of this project is to **analyze the dataset using Pandas and generate useful insights**.

---

# 2. Project Objectives

The objectives of this project are:

- Perform **data exploration using Pandas**
- Clean and preprocess the dataset
- Analyze **content distribution**
- Identify **top producing countries**
- Analyze **genre popularity**
- Study **content growth trends**
- Perform **groupby aggregation**
- Generate meaningful **data insights**

## 3. Import Libraries

In [2]:
import pandas as pd
import numpy as np

## 4. Load Dataset

In [3]:
df = pd.read_csv("streaming_content_dataset_500.csv")

## 5.Basic Data Exploration

### i).Head

In [4]:
df.head()

,content_id,type,title,director,country,genre,rating,release_year,date_added,duration,views_millions
0,C0001,Movie,Title_1,Director_32,Canada,Action,TV-MA,2000,2023-04-26,115 min,26.52
1,C0002,Movie,Title_2,Director_4,India,Thriller,PG,2018,2019-09-25,84 min,126.83
2,C0003,Movie,Title_3,Director_84,Spain,Sci-Fi,PG,2017,2017-03-25,171 min,112.85
3,C0004,TV Show,Title_4,Director_98,UK,Sci-Fi,PG-13,2025,2024-09-30,1 Seasons,70.19
4,C0005,Movie,Title_5,Director_12,South Korea,Comedy,PG-13,2024,2018-10-10,93 min,212.03

### ii) Check dataset shape

In [5]:
df.shape

(500, 11)

### iii) Check columns

In [6]:
df.columns

Index(['content_id', 'type', 'title', 'director', 'country', 'genre', 'rating',
       'release_year', 'date_added', 'duration', 'views_millions'],
      dtype='str')

### iv) Check data types

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   content_id      500 non-null    str
 1   type            500 non-null    str
 2   title           500 non-null    str
 3   director        500 non-null    str
 4   country         500 non-null    str
 5   genre           500 non-null    str
 6   rating          500 non-null    str
 7   release_year    500 non-null    int64
 8   date_added      500 non-null    str
 9   duration        500 non-null    str
 10  views_millions  500 non-null    float64
dtypes: float64(1), int64(1), str(9)
memory usage: 74.9 KB

### v) Summary statistics

In [8]:
df.describe()

       release_year  views_millions
count    500.000000      500.000000
mean    2012.968000      121.313000
std        7.847174       72.717409
min     2000.000000        1.320000
25%     2006.000000       58.547500
50%     2013.000000      114.055000
75%     2020.000000      184.540000
max     2025.000000      249.540000

## 6.Check Missing Values

In [9]:
df.isnull().sum()

content_id        0
type              0
title             0
director          0
country           0
genre             0
rating            0
release_year      0
date_added        0
duration          0
views_millions    0
dtype: int64

### If missing values exist, handle them using:

In [10]:
df.fillna("Unknown", inplace=True)

,content_id,type,title,director,country,genre,rating,release_year,date_added,duration,views_millions
0,C0001,Movie,Title_1,Director_32,Canada,Action,TV-MA,2000,2023-04-26,115 min,26.52
1,C0002,Movie,Title_2,Director_4,India,Thriller,PG,2018,2019-09-25,84 min,126.83
2,C0003,Movie,Title_3,Director_84,Spain,Sci-Fi,PG,2017,2017-03-25,171 min,112.85
3,C0004,TV Show,Title_4,Director_98,UK,Sci-Fi,PG-13,2025,2024-09-30,1 Seasons,70.19
4,C0005,Movie,Title_5,Director_12,South Korea,Comedy,PG-13,2024,2018-10-10,93 min,212.03
...,...,...,...,...,...,...,...,...,...,...,...
495,C0496,Movie,Title_496,Director_31,USA,Drama,TV-MA,2022,2020-05-22,122 min,23.16
496,C0497,Movie,Title_497,Director_20,India,Adventure,G,2018,2022-07-03,143 min,181.17
497,C0498,Movie,Title_498,Director_59,Germany,Documentary,R,2008,2022-03-24,109 min,13.47
498,C0499,Movie,Title_499,Director_47,Japan,Sci-Fi,TV-MA,2001,2024-07-22,117 min,29.86
499,C0500,Movie,Title_500,Director_85,UK,Romance,PG-13,2000,2024-07-21,97 min,223.74

## 7.Filtering Data

### i) Filter only movies:

In [15]:
movies = df[df["type"] == "Movie"]

### ii) Filter TV shows:

In [12]:
tv_shows = df[df["type"] == "TV Show"]

### iii) Filter content released after 2015:

In [13]:
recent_content = df[df["release_year"] > 2015]

## 8.Sorting Data

### i)Sort by newest content:

In [16]:
df.sort_values(by="release_year", ascending=False).head(10)

,content_id,type,title,director,country,genre,rating,release_year,date_added,duration,views_millions
27,C0028,TV Show,Title_28,Director_32,Canada,Thriller,TV-14,2025,2024-08-30,2 Seasons,112.70
19,C0020,TV Show,Title_20,Director_8,Canada,Comedy,G,2025,2018-06-13,4 Seasons,183.24
426,C0427,Movie,Title_427,Director_92,UK,Romance,G,2025,2016-06-18,123 min,6.46
423,C0424,TV Show,Title_424,Director_117,Australia,Drama,TV-MA,2025,2023-04-12,6 Seasons,175.44
429,C0430,TV Show,Title_430,Director_84,Japan,Action,TV-MA,2025,2022-03-03,8 Seasons,242.22
453,C0454,Movie,Title_454,Director_76,Spain,Sci-Fi,G,2025,2022-11-08,159 min,104.20
181,C0182,TV Show,Title_182,Director_42,Australia,Horror,TV-14,2025,2021-05-30,4 Seasons,38.56
172,C0173,Movie,Title_173,Director_107,Japan,Comedy,R,2025,2021-12-06,138 min,211.28
126,C0127,Movie,Title_127,Director_87,Spain,Action,G,2025,2020-03-20,116 min,110.99
100,C0101,Movie,Title_101,Director_96,Australia,Documentary,R,2025,2018-06-13,156 min,31.96

### ii) Sort by highest views:

In [17]:
df.sort_values(by="views_millions", ascending=False).head(10)

,content_id,type,title,director,country,genre,rating,release_year,date_added,duration,views_millions
215,C0216,Movie,Title_216,Director_58,USA,Romance,TV-14,2022,2019-12-24,124 min,249.54
489,C0490,Movie,Title_490,Director_33,Spain,Drama,TV-14,2012,2024-10-30,161 min,248.68
152,C0153,Movie,Title_153,Director_75,Spain,Romance,R,2008,2022-01-01,161 min,248.66
93,C0094,TV Show,Title_94,Director_20,UK,Documentary,G,2015,2015-10-31,1 Seasons,248.49
288,C0289,TV Show,Title_289,Director_97,USA,Action,TV-14,2007,2021-01-19,4 Seasons,248.38
356,C0357,TV Show,Title_357,Director_98,France,Adventure,PG,2017,2024-03-23,1 Seasons,247.45
438,C0439,TV Show,Title_439,Director_71,India,Romance,TV-14,2005,2023-03-18,2 Seasons,246.33
51,C0052,TV Show,Title_52,Director_45,Japan,Sci-Fi,TV-14,2001,2016-03-20,7 Seasons,246.07
70,C0071,TV Show,Title_71,Director_93,UK,Horror,PG,2010,2022-07-02,7 Seasons,245.20
160,C0161,TV Show,Title_161,Director_74,Canada,Sci-Fi,TV-14,2003,2023-07-21,5 Seasons,243.66

## 9. Content Distribution

### i) Count Movies vs TV Shows:

In [18]:
df["type"].value_counts()

type
TV Show    262
Movie      238
Name: count, dtype: int64

## 10. Country Analysis

### i) Top countries producing content:

In [19]:
df["country"].value_counts().head(10)

country
India          62
Spain          59
UK             58
France         54
Germany        51
USA            50
South Korea    44
Australia      44
Canada         42
Japan          36
Name: count, dtype: int64

### ii) Group by country:

In [20]:
df.groupby("country")["title"].count().sort_values(ascending=False)

country
India          62
Spain          59
UK             58
France         54
Germany        51
USA            50
South Korea    44
Australia      44
Canada         42
Japan          36
Name: title, dtype: int64

## 11.Genre Analysis

### i) Most popular genres:

In [21]:
df["genre"].value_counts()

genre
Romance        66
Comedy         62
Documentary    60
Sci-Fi         59
Adventure      58
Thriller       56
Action         48
Horror         48
Drama          43
Name: count, dtype: int64

## 12. Time-Based Analysis

### i) Convert date column to datetime:

In [22]:
df["date_added"] = pd.to_datetime(df["date_added"])

### ii) Extract year added:

In [23]:
df["year_added"] = df["date_added"].dt.year

### iii) Content added per year:

In [24]:
df["year_added"].value_counts().sort_index()

year_added
2015    39
2016    56
2017    39
2018    49
2019    57
2020    48
2021    46
2022    58
2023    54
2024    54
Name: count, dtype: int64

## 13. GroupBy Aggregation

### i) Average views by genre:

In [25]:
df.groupby("genre")["views_millions"].mean()

genre
Action         128.783750
Adventure      132.139138
Comedy         131.947903
Documentary    119.038833
Drama          131.692558
Horror         107.038750
Romance        112.671364
Sci-Fi         121.725593
Thriller       108.374107
Name: views_millions, dtype: float64

### ii) Average views by country:

In [26]:
df.groupby("country")["views_millions"].mean()

country
Australia      102.443864
Canada         124.682143
France         106.200741
Germany        118.113725
India          132.567581
Japan          127.204444
South Korea    114.801818
Spain          125.762373
UK             135.578448
USA            120.406400
Name: views_millions, dtype: float64

### iii) Content count by release year:

In [27]:
df.groupby("release_year").size()

release_year
2000    21
2001    25
2002    20
2003    12
2004    22
2005    20
2006    12
2007    19
2008    14
2009    18
2010    19
2011    17
2012    19
2013    16
2014    23
2015    10
2016    13
2017    21
2018    27
2019    16
2020    19
2021    21
2022    26
2023    21
2024    25
2025    24
dtype: int64

## 14. Pivot Table Analysis

### Create pivot table:

In [28]:
pd.pivot_table(
    df,
    index="type",
    values="views_millions",
    aggfunc="mean"
)

         views_millions
type
Movie        120.109538
TV Show      122.406221

## 15. Feature Engineering

### Create a new column content_age:

In [30]:
df["content_age"] = 2026 - df["release_year"]

In [31]:
df.head(10)

,content_id,type,title,director,country,genre,rating,release_year,date_added,duration,views_millions,year_added,content_age
0,C0001,Movie,Title_1,Director_32,Canada,Action,TV-MA,2000,2023-04-26,115 min,26.52,2023,26
1,C0002,Movie,Title_2,Director_4,India,Thriller,PG,2018,2019-09-25,84 min,126.83,2019,8
2,C0003,Movie,Title_3,Director_84,Spain,Sci-Fi,PG,2017,2017-03-25,171 min,112.85,2017,9
3,C0004,TV Show,Title_4,Director_98,UK,Sci-Fi,PG-13,2025,2024-09-30,1 Seasons,70.19,2024,1
4,C0005,Movie,Title_5,Director_12,South Korea,Comedy,PG-13,2024,2018-10-10,93 min,212.03,2018,2
5,C0006,TV Show,Title_6,Director_69,India,Sci-Fi,G,2025,2015-06-27,8 Seasons,138.46,2015,1
6,C0007,TV Show,Title_7,Director_6,Canada,Documentary,G,2018,2017-02-26,2 Seasons,213.97,2017,8
7,C0008,Movie,Title_8,Director_82,Japan,Action,PG-13,2012,2018-02-12,138 min,89.46,2018,14
8,C0009,TV Show,Title_9,Director_78,UK,Adventure,TV-MA,2022,2022-08-31,2 Seasons,61.96,2022,4
9,C0010,TV Show,Title_10,Director_88,Japan,Drama,PG,2012,2018-01-10,4 Seasons,205.63,2018,14

# Key-Insights

- Movies dominate the platform
The dataset contains more movies than TV shows.

- Certain countries produce more content
Countries like USA, India, and UK contribute the most content.

- Some genres are significantly more popular
Genres such as Drama, Action, and Comedy appear most frequently.

- High-view content varies across genres
Some genres receive higher average views compared to others.

- Content production increased in recent years
More content has been released in recent years compared to earlier periods.

# 20. Conclusion
This project demonstrates how Pandas can be used to analyze streaming platform data effectively.

Skills practiced in this project include:

- Data loading

- Data cleaning

- Filtering

- Sorting

- Aggregation

- Pivot tables

- Feature engineering

- Insight generation